package:
  name: kvxopt
  version: 1.3.0.1
source:
  sha256: 85946e7812c8233a1fc923cf650a116db83d80d0dedd733a7a0428610008e74f
  url: https://files.pythonhosted.org/packages/38/2a/275cbed750339e8671950f8ae6c3d546b937815edd5e0ed518ec1446564e/kvxopt-1.3.0.1.tar.gz
  patches:
    - kvxopt.patch
requirements:
  run:
    - F2CLAPACK
    - SuiteSparse
test:
  imports:
    - kvxopt
    - kvxopt.amd
    - kvxopt.base
    - kvxopt.blas
    - kvxopt.dense
    - kvxopt.klu
    - kvxopt.lapack
    - kvxopt.sparse
    - kvxopt.umfpack
